# Generated by Django 4.0.5 on 2023-04-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_datarahasia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='period',
            field=models.BigIntegerField(),
        ),
    ]
