# Generated by Django 4.0.5 on 2023-04-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('execdate', models.DateTimeField()),
                ('period', models.IntegerField()),
            ],
        ),
    ]
